org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
loom.platform=forge

mod_id=ftbquestskubejs
mod_name=FTB Quests KubeJS Events
mod_version=0.1.0
maven_group=dev.questjs
archives_base_name=ftb-quests-kubejs
mod_author=Questjs

minecraft_version=1.19.2
forge_version=43.2.11
architectury_version=6.5.82
rhino_version=1902.2.2-build.280
kubejs_version=1902.6.2-build.73
ftb_quests_version=1902.5.10-build.497
