org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=ftbquestskubejs
mod_name=FTB Quests KubeJS Events
mod_version=0.1.0
maven_group=dev.questjs
archives_base_name=ftb-quests-kubejs
mod_author=Questjs

minecraft_version=1.21.1
neoforge_version=21.1.213
kubejs_version=2101.7.2-build.374
ftb_quests_version=2101.1.34
