modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ftbquestskubejs"
version="${version}"
displayName="FTB Quests KubeJS Events"
authors="Questjs"
description='''Client-side KubeJS events for opening FTB Quests chapter groups, chapters, and tasks.'''

[[dependencies.ftbquestskubejs]]
modId="neoforge"
type="required"
versionRange="[26.1.2.71,26.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.ftbquestskubejs]]
modId="kubejs"
type="required"
versionRange="[8.0.4,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.ftbquestskubejs]]
modId="ftbquests"
type="required"
versionRange="[26.1.2.7,)"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config="ftbquestskubejs.mixins.json"
