org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
loom.platform=forge

mod_id=ftbquestskubejs
mod_name=FTB Quests KubeJS Events
mod_version=1.0.0
maven_group=dev.questjs
archives_base_name=ftb-quests-kubejs
mod_author=Questjs

minecraft_version=1.20.1
forge_version=47.2.19
architectury_version=9.1.12
kubejs_version=2001.6.5-build.26
ftb_quests_version=2001.4.22
