org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=ftbquestskubejs
mod_name=FTB Quests KubeJS Events
mod_version=1.0.0
maven_group=dev.questjs
archives_base_name=ftb-quests-kubejs
mod_author=Questjs

minecraft_version=26.1.2
neoforge_version=26.1.2.84
kubejs_version=26.1.2-8.0.4+neoforge
kubejs_url=https://cdn.modrinth.com/data/umyGl7zF/versions/Voaox2kE/kubejs-neoforge-26.1.2-8.0.4.jar
rhino_version=2101.2.8-build.91
ftb_quests_version=26.1.2.7
