modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="ftbquestskubejs"
version="${version}"
displayName="FTB Quests KubeJS Events"
authors="Questjs"
description='''Client-side KubeJS events for opening FTB Quests chapter groups, chapters, and tasks.'''

[[dependencies.ftbquestskubejs]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.ftbquestskubejs]]
modId="kubejs"
mandatory=true
versionRange="[1902.6.2,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.ftbquestskubejs]]
modId="ftbquests"
mandatory=true
versionRange="[1902.5.10,)"
ordering="AFTER"
side="CLIENT"
