org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=ftbquestskubejs
mod_name=FTB Quests KubeJS Events
mod_version=1.0.0
maven_group=dev.questjs
archives_base_name=ftb-quests-kubejs
mod_author=Questjs

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
architectury_version=9.1.12
kubejs_version=2001.6.5-build.26
ftb_quests_version=2001.4.22
